[project]
name = "red-eye-detector"
version = "0.1.0"
description = ""
authors = [
    {name = "Timur",email = "chasodeitonny03@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pandas (==2.2.3)",
    "torch (>=2.11.0,<3.0.0)",
    "torchvision (>=0.26.0,<0.27.0)",
    "mlflow (>=3.12.0,<4.0.0)",
    "minio (>=7.2.20,<8.0.0)",
    "psycopg2 (>=2.9.12,<3.0.0)",
    "path (>=17.1.1,<18.0.0)",
    "onnx (>=1.21.0,<2.0.0)",
    "onnxruntime (>=1.26.0,<2.0.0)",
    "onnxscript (>=0.7.0,<0.8.0)",
    "bentoml (>=1.4.39,<2.0.0)",
    "mediapipe (==0.10.14)",
    "uvicorn (>=0.47.0,<0.48.0)",
    "confluent-kafka (>=2.14.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "red-eye-detector"
version = "0.1.0"
description = ""
authors = ["Timur"]
package-mode = false


[dependency-groups]
annotation = [
    "label-studio (>=1.23.0,<2.0.0)"
]
